# Generated by Django 4.2.13 on 2024-06-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_answer_views_question_views_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_count',
            field=models.IntegerField(default=0),
        ),
    ]
